// File generated by Blink v0.17.4 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace Common {
	export namespace Shared {
		type EnemyType = "Normal" | "Speedy" | "Tanky" | "MiniBoss" | "Boss"
		type InventoryTower = { Exp: number, Name: string, Level: number }
		type PlayerData = { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }
	}
	export namespace Client {
		type InputAction = { Action: string, State: unknown, Key: unknown }
	}
	export namespace Server {
	}
}
export declare const entityRemoved: {
	on: (Listener: (Value: number) => void) => (() => void)
}
export declare namespace Enemy {
	export const enemyAdded: {
		on: (Listener: (Value: { ModelName: string, Type: "Normal" | "Speedy" | "Tanky" | "MiniBoss" | "Boss", Air: boolean, Speed: number, MaxHealth: number, T: number }) => void) => (() => void)
	}
}
export declare namespace Tower {
	export const towerAdded: {
		on: (Listener: (Value: { TowerName: string, Owner: number, Position: Vector3 }) => void) => (() => void)
	}
	export const placeTower: {
		fire: (Value: { Origin: Vector3, Direction: Vector3, Slot: number }) => void
	}
}
