// File generated by Blink v0.17.4 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare namespace Shared {
	type EnemyType = "Normal" | "Speedy" | "Tanky" | "MiniBoss" | "Boss"
	type InventoryTower = { Exp: number, Name: string, Level: number }
	type PlayerData = { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }
}
export declare namespace Client {
	type InputAction = { Action: string, State: unknown, Key: unknown }
}
export declare namespace Server {
}
