// File generated by Blink v0.17.4 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace Common {
	export namespace Shared {
		type EnemyType = "Normal" | "Speedy" | "Tanky" | "MiniBoss" | "Boss"
		type InventoryTower = { Exp: number, Name: string, Level: number }
		type PlayerData = { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }
	}
	export namespace Client {
		type InputAction = { Action: string, State: unknown, Key: unknown }
	}
	export namespace Server {
	}
}
export declare const replicateData: {
	fire: (Player: Player, Value: { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }) => void
	fireAll: (Value: { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }) => void
	fireExcept: (Except: Player, Value: { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }) => void
	fireList: (List: Player[], Value: { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }) => void
}
export declare const requestData: {
	on: (Listener: (Player: Player, Value: void) => { Gold?: number | undefined, Silver?: number | undefined, Level?: number | undefined, Exp?: number | undefined, MaxTowers?: number | undefined, TowersInventory?: Map<string, { Exp: number, Name: string, Level: number }> | undefined, Loadout?: string[] | undefined }) => void
}
